### ISSUE TITLE
why compress spaces when you could *extend them*

### ISSUE THREAD

**Issue by walksanatora** [TheEpicBlock/smunnel#2]
just allow us to make them Longer
after all who doesen't love a 1-block long hallway that streches across the world (if little tiles/bits+chisel worked we could make massive hallways in no space at all)

**Comment by TheEpicBlock** [comment]
Uhm, this already works :). Just make the scaling factor smaller than one

**Comment by walksanatora** [comment]
![image](https://media.tenor.com/GryShD35-psAAAAM/troll-face-creepy-smile.gif)
