### ISSUE TITLE
smunnel keeps crashing

### ISSUE THREAD

**Issue by walksanatora** [TheEpicBlock/smunnel#3]
https://crashy.net/D9kfqqttWCST44h7NcRG
the command i ran is ... well it deleted my works but it was basically
`/smunnel add 10 10 10 13 13 13 SOUTH 10`
which let me know that a internal error occured in the command, then a few seconds later the server would crash

**Comment by TheEpicBlock** [comment]
Yeah so, the direction argument is kind of whack. It needs to be `x`, `y` or `z`

**Comment by walksanatora** [comment]
yep that was it
